// @ts-check

const VALIDATORS = {
  REQUIRED: 'REQUIRED',
  FORMAT: 'FORMAT',
  INCORRECT: 'INCORRECT',
  INVALID: 'INVALID',
  MIN_LENGTH: 'MIN_LENGTH',
  MAX_LENGTH: 'MAX_LENGTH',
  LENGTH: 'LENGTH',
  CORRUPT: 'CORRUPT',
  WITHOUT: 'WITHOUT',
  EXIST: 'EXIST',
  NOEXIST: 'NOEXIST'
}

export default VALIDATORS
